[project]
name = "typst-resume"
version = "0.1.0"
description = "Typst-based resume template and generator"
requires-python = ">=3.13"
dependencies = [
    "watchfiles>=1.1.1",
]

[project.scripts]
watch = "watch:main"
generate = "generate:main"
